config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :books do
    resources :notification_requests, only: [:create]
    resources :branches, only: [] do
      resources :copies, only: [:create]
    end
  end

  resources :branches, except: [:destroy]

  resources :copies, only: [:destroy] do
    member do
      post :restore
    end
  end

  resources :checkouts, only: [:index, :create, :destroy] do
    collection do
      get :admin_index
    end
  end

end

app/models/branch.rb
class Branch < ApplicationRecord

  has_many :copies
  has_many :books, through: :copies

  validates_presence_of :name

  def carries_copy_of?(book)
    copies_of(book).size.positive?
  end

  def carries_available_copy_of?(book)
    available_copies_of(book).size.positive?
  end

  def copies_of(book)
    book.copies_at(self)
  end

  def available_copies_of(book)
    copies_of(book).available
  end

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :require_admin!, except: [:show]
  before_action :set_branch, only: [:show, :edit, :update]

  def index
    @branches = Branch.all
  end

  def show; end

  def new
    @branch = Branch.new
  end

  def create
    @branch = Branch.new(branch_params)
    if @branch.save
      redirect_to @branch, notice: 'Branch created successfully'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @branch.update(branch_params)
      redirect_to @branch, notice: 'Branch updated successfully'
    else
      render :edit
    end
  end

  private

  def set_branch
    @branch = Branch.find(params[:id])
  end

  def branch_params
    params.require(:branch).permit(:name, :address, :phone_number)
  end
end

app/views/branches/_form.html.erb
<%= simple_form_for(@branch) do |f|  %>

  <div class="row">
    <div class="col-md">
      <%= f.input :name %>
    </div>
  </div>

  <div class="row">
    <div class="col-md">
      <%= f.input :address, as: :text %>
    </div>
  </div>

  <div class="row">
    <div class="col-md">
      <%= f.input :phone_number, type: :tel %>
    </div>
  </div>

  <%= f.button :submit, class: 'btn-primary' %>
  <%= link_to 'Cancel', branches_path, class: 'btn btn-dark' %>

<% end %>

app/views/branches/edit.html.erb
<h2>Editing Branch (“<%= @branch.name %>”)</h2>

<%= render partial: 'form' %>

app/views/branches/index.html.erb
<h1>Branches</h1>

<div class="table-responsive row col">
  <table class="table table-hover">
    <thead class="thead-light">
    <tr class="row">
      <th class="col" scope="col">Name</th>
      <th class="col-4" scope="col">Address</th>
      <th class="col" scope="col">Phone Number</th>
      <th class="col-2" scope="col" colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @branches.each do |branch| %>
      <tr class="row">
        <td class="col text-nowrap"><%= branch.name %></td>
        <td class="col-4 text-truncate"><%= branch.address %></td>
        <td class="col text-nowrap"><%= branch.phone_number %></td>
        <td class="col-2 text-nowrap">
          <%= link_to 'Show', branch %>
          |
          <%= link_to 'Edit', edit_branch_path(branch) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<h2>Create a New Branch</h2>

<%= render partial: 'form' %>

app/views/branches/show.html.erb
  <h3><%= @branch.name %></h3>


    <div class="card mb-2">
      <div class="card-header">Address</div>
      <div class="card-body">
        <% if @branch.address.present? %>
          <address>
            <%= simple_format(@branch.address) %>
          </address>
          <%= link_to 'View Map', google_map_pin_link(@branch.address) %>
        <% else %>
          -
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-header">Phone Number</div>
      <div class="card-body">
        <% if @branch.phone_number.present? %>
          <%= link_to @branch.phone_number, "tel:#{@branch.phone_number}" %>
        <% else %>
          -
        <% end %>
      </div>
    </div>

    <% if current_user&.is_admin? %>
      <div class="text-right">
        <%= link_to 'Edit', edit_branch_path(@branch) %>
        |
        <%= link_to 'Branches', branches_path %>
      </div>
    <% end %>