config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :books do
    resources :notification_requests, only: [:create]
    resources :branches, only: [] do
      resources :copies, only: [:create]
    end
  end

  resources :branches, except: [:destroy]

  resources :copies, only: [:destroy] do
    member do
      post :restore
    end
  end

  resources :checkouts, only: [:index, :create, :destroy] do
    collection do
      get :admin_index
    end
  end

end

app/models/book.rb
class Book < ApplicationRecord
  # title
  # author
  # genre
  # subgenre
  # pages
  # publisher

  default_scope { order(author: :asc) }

  has_many :copies
  has_many :branches, through: :copies

  def undestroyed_copies
    copies.active
  end

  def destroyed_copies
    copies.inactive
  end

  def available_copies
    copies.available
  end

  def available_copies_at(branch)
    available_copies.where(branch: branch)
  end

  def copies_at(branch)
    undestroyed_copies.where(branch: branch)
  end

  def destroyed_copies_at(branch)
    destroyed_copies.where(branch: branch)
  end

  def generate_count_caches
    copies_array = copies.to_a
    active_copies_array = copies_array.select(&:active?)
    available_copies_array = active_copies_array.select(&:available?)
    @max_copy_count = active_copies_array.size
    @available_copy_count = available_copies_array.size

    av_by_branch_id = available_copies_array.group_by { |copy| copy.branch.id }
    @available_copy_count_by_branch_id = Hash.new(0)
    av_by_branch_id.each do |id, copies|
      @available_copy_count_by_branch_id[id] = copies.size
    end
  end
  def cached_available_copy_count_at(branch)
    @available_copy_count_by_branch_id[branch.id]
  end
  def cached_available_copy_count
    @available_copy_count
  end
  def cached_max_copy_count
    @max_copy_count
  end

  validates_presence_of :title
  validates_uniqueness_of :title, scope: [:author, :publisher]

  validates_length_of :genre, minimum: 3
  validates_length_of :author, minimum: 3, allow_blank: true, allow_nil: true
  validates_length_of :publisher, minimum: 3, allow_blank: true, allow_nil: true

  validates_presence_of :pages
  validates_numericality_of :pages, only_integer: true, greater_than: 0

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_admin!, except: [:index, :show]

  before_action :set_book, only: [:show, :edit, :update]
  before_action :set_branches, only: [:index, :show]

  def index
    @books = Book.includes(copies: [:branch]).all
    @books.each(&:generate_count_caches)
  end

  def show
    @book.generate_count_caches
  end

  def new
    @book = Book.new(pages: 0)
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book created successfully.'
    else
      flash.now[:error] = 'Could not save book'
      render action: 'new'
    end

  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book updated successfully.'
    else
      flash.now[:error] = 'Could not save book'
      render action: 'edit'
    end

  end

  private

  def set_book
    @book = Book.includes(copies: [:branch]).find(params[:id])
  end

  def set_branches
    @branches = Branch.all
  end

  def book_params
    params.require(:book).permit(:title, :author,
                                 :genre, :subgenre,
                                 :pages, :publisher)
  end
end

app/views/books/_book.html.erb
<div class="book book-<%= book.id %> col-md-6 p-1">

  <div class="list-group">

    <div class="list-group-item list-group-item-action">

      <%= link_to book_path(book), class: 'd-flex justify-content-between align-items-center' do %>

        <%= book.title %>

        <span class="badge badge-dark badge-pill">
          <%= book.cached_available_copy_count %>
          /
          <%= pluralize(book.cached_max_copy_count, 'copy') %>
        </span>

      <% end %>

      <p class="text-muted">
        <%= book.author.blank? ? 'Author Unknown' : book.author %>
      </p>

      <% if mode==:display %>
        <p class="card-text">
          Published by <%= book.publisher.blank? ? '(Unknown)' : book.publisher %>
        </p>

        <p class="card-text">
          <%= book.genre.titleize %> <%= wrap_parens(book.subgenre) %>
        </p>

        <p class="card-text">
          <%= book.pages %> pages
        </p>
      <% end %>

      <% unless current_user.nil? %>
        <div class="text-right">
          <% if book.cached_available_copy_count.zero? %>

            Out of Copies (
            <% if current_user.notification_pending_for?(book) %>
              Notification Pending
            <% else %>
              <%= link_to 'Notify me when available', book_notification_requests_path(book), method: :post %>
            <% end %>
            )

          <% else %>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Borrow</button>
              <div class="dropdown-menu">
                <% @branches.each do |branch| %>
                  <% if book.cached_available_copy_count_at(branch).positive? %>
                    <%= button_to checkouts_path,
                                method: :post,
                                params: {book_id: book.id,
                                         branch_id: branch.id},
                                class: 'dropdown-item' do %>
                      <%= branch.name %>
                      (<%= book.cached_available_copy_count_at(branch) %>)
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>


          <% end %>
        </div>
      <% end %>


    </div>

    <% if current_user&.is_admin? %>
      <div class="list-group-item text-right"> Admin Only:
        <%= link_to 'Edit this Book', edit_book_path(book) %>
      </div>
    <% end %>

  </div>

</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f|  %>

  <div class="row">
    <div class="col-md-10">
      <%= f.input :title %>
    </div>
    <div class="col-md-2">
      <%= f.input :pages %>
    </div>
  </div>

  <div class="row">
    <div class="col-md">
      <%= f.input :author %>
    </div>
    <div class="col-md">
      <%= f.input :publisher %>
    </div>
  </div>

  <div class="row">
    <div class="col-md">
      <%= f.input :genre %>
    </div>
    <div class="col-md">
      <%= f.input :subgenre %>
    </div>
  </div>

  <%= f.button :submit, class: 'btn-primary' %>
  <%= link_to 'Cancel', books_path, class: 'btn btn-dark' %>

<% end %>

app/views/books/edit.html.erb
<h2>Editing Book (“<%= @book.title %>”)</h2>

<%= render partial: 'form' %>

app/views/books/index.html.erb
<h2>Books</h2>

<%= link_to new_book_path, class: 'btn btn-primary' do %>
    Create New Book
<% end if current_user&.is_admin? %>

<div class="books row">

  <%= render partial: 'book', collection: @books, locals: {mode: :list} %>

</div>

app/views/books/new.html.erb
<h2>Create a New Book</h2>

<%= render partial: 'form' %>

app/views/books/show.html.erb
<%= link_to 'Return to library', books_path %>

<div class="books row">

    <%= render partial: 'book', object: @book, locals: {mode: :display} %>

    <div class="col-md-6">
      <h2>Copies</h2>

      <% @branches.each do |branch| %>
        <h3><%= link_to branch.name, branch %></h3>

        <%= link_to book_branch_copies_path(@book, branch), method: :post do %>
          Add Copy
        <% end if current_user&.is_admin? %>

        <% branch.copies_of(@book).each do |copy| %>
          <div class="d-flex justify-content-between align-items-center">
            <span>
              Copy: <%= copy_location(copy, current_user) %>
            </span>
            <%= link_to copy_path(@book, branch, copy),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } do %>
              Delete Copy
            <% end if current_user&.is_admin? %>
          </div>
        <% end %>

        <% if current_user&.is_admin? %>
          <p>
            <a class="" data-toggle="collapse" href="#destroyedCopies_<%= branch.id %>" role="button" aria-expanded="false" aria-controls="destroyedCopies">
              Show deleted copies
            </a>
          </p>
          <div class="collapse" id="destroyedCopies_<%= branch.id %>">
            <div class="card card-body">
              <% @book.destroyed_copies_at(branch).each do |copy| %>
                <div class="d-flex justify-content-between align-items-center">
                  <span>Copy: (destroyed)</span>
                  <%= link_to restore_copy_path(copy),
                              method: :post,
                              data: { confirm: 'Are you sure?' } do %>
                    Restore Copy
                  <% end %>
                </div>
              <% end %>
              <% if @book.destroyed_copies_at(branch).size.zero? %>
                No copies have been destroyed
              <% end %>
            </div>
          </div>

        <% end %>

      <% end %>
    </div>
</div>