config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :books do
    resources :notification_requests, only: [:create]
    resources :branches, only: [] do
      resources :copies, only: [:create]
    end
  end

  resources :branches, except: [:destroy]

  resources :copies, only: [:destroy] do
    member do
      post :restore
    end
  end

  resources :checkouts, only: [:index, :create, :destroy] do
    collection do
      get :admin_index
    end
  end

end

app/models/checkout.rb
class Checkout < ApplicationRecord
  # checked_out_at
  # due_at
  # checked_in_at

  belongs_to :copy
  belongs_to :user

  scope :active, -> { where(checked_in_at: nil) }
  scope :overdue, ->(at_utc) { where('due_at < ?', at_utc) }

  before_create :set_due_date


  # @param [Object] at_time_utc     The time in UTC (e.g. Time.current)
  def overdue(at_time_utc)
    user_zone = user.time_zone

    user_due_at = due_at.in_time_zone(user_zone)
    user_current = at_time_utc.in_time_zone(user_zone)

    user_due_at < user_current
  end

  private

  def set_due_date
    # book must be returned one week after checkout date
    local_checkout = checked_out_at.in_time_zone(user.time_zone)
    self.due_at = local_checkout.end_of_day + 1.week
  end

end

# Checkout.all.map do |c|
#   {
#     due_at: c.due_at,
#     due_at_local: c.due_at.in_time_zone(c.user.time_zone),
#     overdue: c.overdue(Time.current)
#   }
# end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def index
    @checkouts = Checkout.active.where(user: current_user)
    render 'user_index'
  end

  def admin_index
    require_admin!

    checkouts = Checkout.active
    @checkouts_by_user_id = {}
    checkouts.each do |checkout|
      @checkouts_by_user_id[checkout.user.id] ||= {
        user: checkout.user,
        checkouts: []
      }
      @checkouts_by_user_id[checkout.user.id][:checkouts] << checkout
    end
    render 'admin_index'
  end

  def create
    book = Book.find(params[:book_id])
    branch = Branch.find(params[:branch_id])
    checkout_copy(acquire_copy(book,branch))
    redirect_back fallback_location: books_path, notice: 'Checkout successful'
  rescue StandardError => e
    redirect_back fallback_location: books_path, alert: e.message
  end

  def destroy
    checkout = Checkout.find(params[:id])
    checkin(checkout)
    notify_waiting_members(checkout.copy.book)
    redirect_back fallback_location: checkouts_path, notice: 'Thanks for returning the book'
  rescue StandardError => e
    redirect_back fallback_location: checkouts_path, alert: e.message
  end

  private

  def acquire_copy(book, branch)
    book.copies_at(branch).available.first.tap do |copy|
      raise('No Copies Available') if copy.nil?
    end
  end

  def checkout_copy(copy)
    checkout_time = Time.current
    ActiveRecord::Base.transaction do
      checkout = Checkout.create(copy: copy,
                                 user: current_user,
                                 checked_out_at: checkout_time)
      raise checkout.errors.full_messages.to_sentence unless checkout.valid?

      copy.update(checked_out_at: checkout_time,
                  checked_out_by: current_user)
      raise copy.errors.full_messages.to_sentence unless copy.valid?
    end
  end

  def checkin(checkout)
    checkin_time = Time.current
    ActiveRecord::Base.transaction do
      checkout.update(checked_in_at: checkin_time)
      raise checkout.errors.full_messages.to_sentence unless checkout.valid?

      copy = checkout.copy
      copy.update(checked_out_at: nil,
                  checked_out_by: nil)
      raise copy.errors.full_messages.to_sentence unless copy.valid?
    end
  end

  def notify_waiting_members(book)
    NotificationRequest.where(book: book).each do |req|
      UserMailer.with(notification_request: req).notification_email.deliver_now
    end
  end
end

app/views/checkouts/_checkout.html.erb
<tr>
  <th scope="row" class="text-nowrap">
    <%= checkout.copy.book.title %>
  </th>
  <td class="text-nowrap">
    <%= checkout.checked_out_at.in_time_zone(checkout.user.time_zone) %>
  </td>
  <td class="text-nowrap">
    <%= checkout.due_at.in_time_zone(checkout.user.time_zone) %>
  </td>
  <% if checkout.user==current_user && display==:user %>
    <td class="text-nowrap">
      <%= button_to 'Return', checkout_path(checkout),
                    method: :delete,
                    class: 'btn btn-primary btn-sm text-right'%>
    </td>
  <% end %>
</tr>

app/views/checkouts/_checkouts_for_user.html.erb
<p><%= pluralize(checkouts.size, 'item', 'items') %> checked out</p>

<% if checkouts.size > 0 %>

<div class="table-responsive">
  <table class="table table-hover">
    <thead class="thead-light">
    <tr>
      <th scope="col">Book</th>
      <th scope="col">Since</th>
      <th scope="col">Due</th>
      <% if user==current_user && display == :user %>
        <th scope="col">Return</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'checkout', collection: checkouts, locals: {display: display} %>
    </tbody>
  </table>
</div>

<% end %>

app/views/checkouts/admin_index.html.erb
<h3>Active Checkouts</h3>

<% @checkouts_by_user_id.each do |_, hash| %>
  <div class="card card-body">
    <h4>User: <%= hash[:user].email %></h4>

    <%= render partial: 'checkouts_for_user',
               locals: { user: hash[:user],
                         checkouts: hash[:checkouts],
                         display: :admin } %>

  </div>
<% end %>

app/views/checkouts/user_index.html.erb
<h3>Active Checkouts</h3>

<%= render partial: 'checkouts_for_user',
           locals: { user: current_user,
                     checkouts: @checkouts,
                     display: :user } %>